config/routes.rb
Starbox::Application.routes.draw do
  root :to => 'beverages#index'
  resources :beverages do
    member do
      post 'vend'
    end
  end
  resources :ingredients do
    collection do
      post 'restock'
    end
  end
end

app/models/beverage.rb
class Beverage < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name, :recipe
  has_one :recipe

  delegate :price, :to => :recipe
  delegate :available?, :to => :recipe

  def vend
    available? ? recipe.make : false
  end
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, :price, :units
  validates_presence_of :name, :price, :units
  has_many :recipe_ingredients

  def available?(qty=1)
    qty <= units ? true : false
  end

  def use(qty)
    self.available?(qty) ? (update_attribute :units, units - qty) : false
  end

  def restock
    update_attribute :units, MAX_INVENTORY
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :beverage
  has_many :recipe_ingredients

  def price
    prices = recipe_ingredients.collect {|r| r.ingredient.price * r.units}
    prices.inject {|sum, x| sum + x}
  end

  def available?
    self.recipe_ingredients.each do |r|
      return false unless r.ingredient.available?(r.units)
    end
    true
  end

  def make
    self.recipe_ingredients.each do |r|
      r.ingredient.use(r.units)
    end
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  attr_accessible :units
  validates_presence_of :units
  validates_presence_of :recipe
  validates_presence_of :ingredient
  belongs_to :recipe
  belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/beverages_controller.rb
class BeveragesController < ApplicationController
  def index
    @beverages = Beverage.all
  end

  def vend
    @beverage = Beverage.find(params[:id])
    if @beverage.available? && @beverage.vend
      render :text => "Thank you! Please enjoy your #{@beverage.name}", :status => 200
    else
      render :text => "Sorry! We are temporarily unable to dispense #{@beverage.name}. Please make a different selection", :status => 200
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_filter :load_ingredients

  def index
  end

  def restock
    @ingredients.each {|ingredient| ingredient.restock}
    flash.now[:notice] = 'Inventory successfully restocked!'
    render :action => :index
  end

  private

  def load_ingredients
    @ingredients = Ingredient.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beverages_helper.rb
module BeveragesHelper
  def formatted_price(price)
    "$#{price}"
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/beverages/index.html.haml
%h1 Welcome to Starbox
%p.lead Please make a selection from the beverage menu below:
%table.beverage_menu
  - @beverages.each do |beverage|
    %tr.menu_row
      %td.name
        %h3= beverage.name
      %td.price
        %h3= formatted_price(beverage.price)
      %td.selection
        = link_to('MAKE SELECTION', 'javascript:void(0)', :class => 'btn btn-large btn-success select-beverage', :url => vend_beverage_url(beverage))
#process_modal{:class => 'modal'}
  %h3 Please wait...
  = image_tag('working.gif', :size=>'50x50')
.vend_result{:class => 'alert alert-success'}

app/views/ingredients/index.html.haml
%h2 Current StarBox Inventory
%p.lead Hit the button below to restock ingredients inventory:
%table.ingredient_list
  %tr.row
    %th 
      %h3 Ingredient
    %th 
      %h3 Units on Hand
  - @ingredients.each do |ingredient|
    %tr.row
      %td.name 
        %h4= ingredient.name
      %td.qty
        %h4= ingredient.units
.action_div
  = link_to('RESTOCK', restock_ingredients_url, :method => :post, :class => 'btn btn-large btn-success') 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Starbox
    = favicon_link_tag
    = stylesheet_link_tag 'application.css', :media => 'screen, projection'
    /[if lt IE 8]
      = stylesheet_link_tag 'ie.css', :media => 'screen, projection'
    = csrf_meta_tag
    = javascript_include_tag 'application'
  %body
    .container
      .masthead
        %ul.nav.nav-pills.pull-right
          %li
            = link_to('Beverage Menu', root_url)
          %li
            = link_to('Inventory', ingredients_url)
        %h2.muted StarBox
      %hr
      .alerts
        = render :partial => 'shared/flashes'
      .jumbotron
        = yield
      %hr
      .footer
        %p Copyright, StarBox Inc., 2013

app/views/shared/_flashes.html.haml
- flash.each do |name, msg|
  - unless msg.blank?
    - case name
      - when :alert, :error then
        = content_tag :div, msg, :class => "alert alert-error"
      - when :success then
        = content_tag :div, msg, :class => "alert alert-success"
      - when :warning then
        = content_tag :div, msg, :class => "alert alert-warning"
      - when :notice then
        = content_tag :div, msg, :class => "alert alert-success"
      - else 
        = content_tag :div, msg, :class => "alert alert-info"